name: bsl-env
channels:
  - defaults
dependencies:
  - anaconda-client
  - anaconda-cloud-auth
  - anaconda-navigator
  - anaconda-project
  - annotated-types
  - archspec
  - attrs
  - backports.tempfile
  - beautifulsoup4
  - boltons
  - Brotli
  - cffi
  - chardet
  - conda
  - conda-build
  - conda-content-trust
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-repo-cli
  - conda-token
  - conda-verify
  - cryptography
  - defusedxml
  - distro
  - filelock
  - future
  - frozendict
  - intervaltree
  - jaraco.classes
  - jinja2
  - jsonpatch
  - jsonschema
  - jsonschema-specifications
  - jupyter_core
  - keyring
  - libmambapy
  - menuinst
  - more-itertools
  - nbformat
  - pathtools
  - pkce
  - pkginfo
  - pycosat
  - pycparser
  - pydantic
  - pywin32-ctypes
  - qtpy
  - referencing
  - requests-toolbelt
  - rpds-py
  - ruamel.yaml
  - ruamel.yaml.clib
  - semver
  - sortedcontainers
  - soupsieve
  - tomli
  - tornado
  - traitlets
  - ujson
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - seaborn
  - statsmodels
  - sympy
  - sqlalchemy
  - torchvision
